[package]
name = "clt_ekubo"
version = "0.1.0"
edition = "2024_07"

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis", rev="2a846ea35adcf066d7525eac39fea0df283e1c1f" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.20.0"}

starknet = "2.9.2"

[dev-dependencies]
snforge_std = "0.35.1"
assert_macros = "2.9.2"

[[target.starknet-contract]]
sierra = true

[[tool.snforge.fork]]
name = "mainnet"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/dqc_sBRTzvDkK83URggtdW4wolmtyqYc"
block_id.number = "1380103"

[scripts]
test = "snforge test"


[profile.dev.cairo]
# unstable-add-statements-code-locations-debug-info = true
# unstable-add-statements-functions-debug-info = true
